
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'ZzbGameSDK_Example' do
  pod 'ZzbGameSDK', :path => '../'

  target 'ZzbGameSDK_Tests' do
    inherit! :search_paths
  end
  
end
